language: node_js
node_js:
  - 0.9.x
  - 0.8
  - 0.6
notifications:
  email:
    on_success: change
    on_failure: change

  irc:
    channels:
      - "irc.freenode.net#node-wiki"
    on_success: always
    on_failure: always

